apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qubh3dlfk-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qubh3dlfk-go 
  name: qubh3dlfk-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: qubh3dlfk-go 
